create:
	protoc -I ./proto \
	--go_out ./api --go_opt paths=source_relative \
	--go-grpc_out ./api --go-grpc_opt paths=source_relative \
	--grpc-gateway_out ./api --grpc-gateway_opt paths=source_relative \
	./proto/beef.proto

clear:
	rm api/*.go